**********************************************************************
*                                                                    *
* PUTMAN2 >>> Put manifest page 2                                    *
*             ENTRY : GID number                                     *
*             EXIT  : None                                           *
*                                                                    *
*    (C)opyright 1984 Personal Touch Software, All Rights Reserved   *
*                                                                    *
**********************************************************************

set color to &FORE/&BACK

@ 4,1 say "       ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
@ 4,39 say "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿"

@ 5,1 say "Item 1 ³"
@ 5,79 say "³"
@ 6,1 say "       ³"
@ 6,79 say "³"
@ 7,1 say "       ³"
@ 7,79 say "³"

@ 8,1 say "       ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
@ 8,39 say "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´"

@ 9,1 say "Item 2 ³"
@ 9,79 say "³"
@ 10,1 say "       ³"
@ 10,79 say "³"
@ 11,1 say "       ³"
@ 11,79 say "³"

@ 12,1 say "       ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
@ 12,39 say "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´"

@ 13,1 say "Item 3 ³"
@ 13,79 say "³"
@ 14,1 say "       ³"
@ 14,79 say "³"
@ 15,1 say "       ³"
@ 15,79 say "³"

@ 16,1 say "       ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
@ 16,39 say "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´"

@ 17,1 say "Item 4 ³"
@ 17,79 say "³"
@ 18,1 say "       ³"
@ 18,79 say "³"
@ 19,1 say "       ³"
@ 19,79 say "³"

@ 20,1 say "       ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ"
@ 20,39 say "ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ"

@ 5,9 say M_UN_NA1
@ 6,9 say M_DESC_1_1
@ 7,9 say M_DESC_2_1
@ 7,64 say M_CNTNO1
@ 7,68 say M_CNTTY1
@ 7,71 say M_QNTY1
@ 7,77 say M_UNIT1

@ 9,9 say M_UN_NA2
@ 10,9 say M_DESC_1_2
@ 11,9 say M_DESC_2_2
@ 11,64 say M_CNTNO2
@ 11,68 say M_CNTTY2
@ 11,71 say M_QNTY2
@ 11,77 say M_UNIT2

@ 13,9 say M_UN_NA3
@ 14,9 say M_DESC_1_3
@ 15,9 say M_DESC_2_3
@ 15,64 say M_CNTNO3
@ 15,68 say M_CNTTY3
@ 15,71 say M_QNTY3
@ 15,77 say M_UNIT3

@ 17,9 say M_UN_NA4
@ 18,9 say M_DESC_1_4
@ 19,9 say M_DESC_2_4
@ 19,64 say M_CNTNO4
@ 19,68 say M_CNTTY4
@ 19,71 say M_QNTY4
@ 19,77 say M_UNIT4

set color to &FORE_OFF/&BACK

return
