pause Insert Utility Services cEnglish Wastrac disk # 1
dir a:/w
del a:*.*
copy \track\*.ce a:
copy \track\*.dir a:
copy \track\*.dat a:
copy \track\*.idx a:
copy \track\trackbu.bat a:
copy \track\track.lmk a:
copy \track\track.lnk a:

pause Insert Utility Services cEnglish Wastrac disk # 2
dir a:/w
del a:*.*
copy \track\*.ce a:
copy \track\*.dir a:
copy \track\*.dat a:
copy \track\*.idx a:
copy \track\trackbu.bat a:
copy \track\track.lmk a:
copy \track\track.lnk a:

